# Generated by Django 3.0.5 on 2020-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('cast', models.TextField(default='', null=True)),
                ('genres', models.CharField(default='', max_length=120, null=True)),
                ('runtimes', models.CharField(default='', max_length=50, null=True)),
                ('countries', models.CharField(default='', max_length=200, null=True)),
                ('language_codes', models.CharField(default='', max_length=125, null=True)),
                ('aspect_ratio', models.CharField(default='', max_length=350, null=True)),
                ('box_office', models.CharField(default='', max_length=350, null=True)),
                ('certificates', models.TextField(default='', null=True)),
                ('air_date', models.CharField(default='', max_length=120, null=True)),
                ('rating', models.CharField(default='', max_length=100, null=True)),
                ('votes', models.CharField(default='', max_length=15, null=True)),
                ('cover_url', models.URLField(blank=True, default='', null=True)),
                ('plot_outline', models.TextField(default='', null=True)),
                ('languages', models.CharField(default='', max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=250)),
                ('year', models.CharField(default='', max_length=350, null=True)),
                ('director', models.CharField(default='', max_length=500, null=True)),
                ('plot', models.TextField(default='', null=True)),
                ('long_imdb_title', models.CharField(default='', max_length=300)),
                ('full_size_cover_url', models.URLField(blank=True, default='', null=True)),
            ],
        ),
    ]
