# Generated by Django 3.0.5 on 2020-05-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagmovies', '0002_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movielist',
        ),
    ]
