# Generated by Django 3.0.5 on 2020-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagmovies', '0004_movies_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
